### ISSUE TITLE
Is it possible to query for subcollections?

### ISSUE THREAD

**Issue by marchv** [sgarciac/fuego#11]
Thanks a lot for a great tool!

But (unfortunately) I made a collection with documents in, which then have collections again. And those collections has documents...

Is is possible to query for those collection-document-collection-documents?

Thanks again!

Cheers!

Best regards,

Jens Schwarzer :)

**Comment by eqinox76** [comment]
Hey Jens,
sure just give the full path to the subcollection you want to query on.
Example:
```
fuego query --limit 1 collection/document/collection 'age==42'
```
Let me know if that works for you.

**Comment by marchv** [comment]
Hi @eqinox76 and thanks a lot - yes that just worked! You are a ⭐️
Cheers! :)

**Comment by kjetilhp** [comment]
> Hey Jens,
> sure just give the full path to the subcollection you want to query on.
> Example:
> 
> ```
> fuego query --limit 1 collection/document/collection 'age==42'
> ```
> 
> Let me know if that works for you.

Maybe this should be part of the documentation :)

**Comment by sgarciac** [comment]
(added to documentation)
