### ISSUE TITLE
Missing documentation: How to set project id, when using emulator

### ISSUE THREAD

**Issue by ath88** [sgarciac/fuego#12]
I get the following:
> ~$ FIRESTORE_EMULATOR_HOST=localhost:9001 fuego collections
> Failed to create client. 
> project id is required to access Firestore

I cant spot anywhere how I can set the project id. What am I doing wrong?

**Comment by ath88** [comment]
I see the latest release doesn't include that feature, the help-text does reveal some documentation when running from the current master branch. Consider this issue for only markdown-documentation.

**Comment by eqinox76** [comment]
Hard to pin down where your issue is. Let me give you a example and thereafter we can figure out what exactly goes wrong.
When i start the firestore emulator:
```
$ gcloud beta emulators firestore start --host-port=localhost:8553
Executing: /google-cloud-sdk/platform/cloud-firestore-emulator/cloud_firestore_emulator start --host=localhost --port=8553
[firestore] API endpoint: http://localhost:8553
[firestore] If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:
[firestore] 
[firestore]    export FIRESTORE_EMULATOR_HOST=localhost:8553
[firestore] 
[firestore] Dev App Server is now running.
[firestore] 
```
I can add data and query it:
```
$ FIRESTORE_EMULATOR_HOST='localhost:8553' go run . add some '{"age":23}'
DJvBvmiJezR0IyBQfZTs
$ FIRESTORE_EMULATOR_HOST='localhost:8553' go run . query some
[
{
    "CreateTime": "2019-11-06T15:19:54.308Z",
    "Data": {
        "age": 23
    },
    "ID": "DJvBvmiJezR0IyBQfZTs",
    "ReadTime": "2019-11-06T15:20:04.269Z",
    "UpdateTime": "2019-11-06T15:19:54.308Z"
}
]
```
Listing all collections is not working:

```
$ FIRESTORE_EMULATOR_HOST='localhost:8553' go run . c
Failed to list collections. 
rpc error: code = PermissionDenied desc = Metadata operations require admin authentication.
exit status 86
```
Which is, if i remember correctly, a issue with the firestore emulator itself.

For reference: I am using fuego commit 0f61114 and Cloud SDK version 261.0.0 (which is quiet outdated).

**Comment by sgarciac** [comment]
@ath88 : you are right, the latest release is not up to date with the master branch documentation. I'll create a new release tonight.

@equinox76 : yep, "collections" was not working in the emulator last time I tried too.

**Comment by sgarciac** [comment]
Release 0.6.0 created
