### ISSUE TITLE
`go get` failed

### ISSUE THREAD

**Issue by ts95** [sgarciac/fuego#13]
This happened when I tried to install it.
```
→ go get github.com/sgarciac/fuego

# cloud.google.com/go/firestore
../../go/src/cloud.google.com/go/firestore/query.go:493:8: undefined: "google.golang.org/genproto/googleapis/firestore/v1".StructuredQuery_FieldFilter_IN
../../go/src/cloud.google.com/go/firestore/query.go:497:8: undefined: "google.golang.org/genproto/googleapis/firestore/v1".StructuredQuery_FieldFilter_ARRAY_CONTAINS_ANY
```

I'm running macOS 10.15 and Go 1.12.6

**Comment by sgarciac** [comment]
Thanks, I'll have a look at it.

**Comment by sgarciac** [comment]
Hello @ts95 , I failed to reproduce the problem. Still, I just updated all the module dependencies, so there is a chance it corrects the problem. Could you please try the go get again?

**Comment by ts95** [comment]
That worked! 🎉
![image](https://user-images.githubusercontent.com/1880556/69081747-f0a7cb80-0a3e-11ea-9aaf-9df516d555f6.png)
