### ISSUE TITLE
Support for arrays in an "input" file?

### ISSUE THREAD

**Issue by egarson** [sgarciac/fuego#16]
Hello and thanks for a great project.
Maybe I missed a beat, but is there a way to import a file containing an array of objects? In your documentation, I would like to be able to provide a **dogS.json**... ^_^
I tried a few ways but none worked....

**Comment by egarson** [comment]
My simple workaround is to use a text document with json objects inside it one per line:
`{"a":1}
{"b":2}`
I can then:
`
[[ -f $1 ]] || { echo "no such file '$1'" && return 1 }
ctr=1
while IFS=$'\n' read -r line; do 
    fuego set data "a$ctr" $line
    (( ctr++ ))
 done < $1`

I thought the above might be helpful for someone else. I tried using `jq` (which is a great tool) to parse "real" json files but the necessary quote escaping escaped me ^_^.
All to say, it would be great to be able to point fuego at a json file containing an array of objects to insert into a given collection....
Cheers!

**Comment by sgarciac** [comment]
Hello @egarson , thanks for the suggestion. I this line would also do the trick, if you want to upload data from a file that contains a json array of objects:

```bash
cat ~/myjson.json | jq -c .[] | sed -e 's/"/"\\""/g' -e 's/.*/"&"/' | xargs -n1 ./fuego add mycollection
```

I think, however, that firestore provides the means for batch loading data, which is probably a better option for large collections.

**Comment by egarson** [comment]
Thanks for that: it has the advantage of keeping the files as valid json.
Cheers
