### ISSUE TITLE
Auto generated IDs are 32 bytes instead of 24 

### ISSUE THREAD

**Issue by tripflex** [sgarciac/fuego#18]
Took me a while to figure out why it was doing this, but turns out it was due to the go lib this project relies on:
https://github.com/googleapis/google-cloud-go/issues/1715

This was a huge issue for me generating IDs with crazy long values, seem all the latest pre-built versions of fuego are impacted by this

ps -- by the way thank you for adding delete handling!

**Comment by tripflex** [comment]
Just tried building from source and still does it as well :(

**Comment by eqinox76** [comment]
Wow thats a surprising change.

**Comment by sgarciac** [comment]
oh wow, thanks for reporting! @tripflex

**Comment by sgarciac** [comment]
@tripflex did you try building fuego with an older version of the go firestore library? It might fix the problem for you in the meantime :(

**Comment by tripflex** [comment]
@sgarciac yeah but had issues with it, had to just revert back to older version of fuego (without delete which is really what i needed), but seems after i brought this up they prompted released an update to fix this in 1.2.0:
https://pkg.go.dev/cloud.google.com/go/firestore@v1.2.0?tab=doc

Looks like would just need to update the dep in this library to use 1.2.0 instead of 1.1.0 (which it was broke in)

**Comment by tripflex** [comment]
https://github.com/googleapis/google-cloud-go/releases/tag/firestore%2Fv1.2.0

**Comment by sgarciac** [comment]
great, I'll upgrade it. Thanks @tripflex

**Comment by tripflex** [comment]
Confirmed it works i built it locally without issues :)
