### ISSUE TITLE
Collection Group queries

### ISSUE THREAD

**Issue by chuckntaylor** [sgarciac/fuego#22]
Is there support for Collection Group queries?
https://firebase.googleblog.com/2019/06/understanding-collection-group-queries.html

If there is, do you have an example?

**Comment by sgarciac** [comment]
Nope, and I honestly I was not even aware they existed. Thanks, I'll be adding them (unless someone wants to take on that task, it should be pretty straightforward to code)

**Comment by sgarciac** [comment]
Done, supported in the current release.
