### ISSUE TITLE
Throws invalid token error for $

### ISSUE THREAD

**Issue by fastfedora** [sgarciac/fuego#29]
While a dollar sign is valid within a property name, `fuego` doesn't appear to allow it:

```
fuego query myCollection '$archived == true'                                                                                                                                                      
Error parsing query '$template' <source>:1:1: invalid token '$'
```

I believe [this line](https://github.com/sgarciac/fuego/blob/master/parser.go#L72) is the one that needs to be changed to allow it. 

In Firestore, property names can have any valid UTF-8 character, though I have found issues when using periods, since that's also used as the field separator. But all other characters should be valid here.

**Comment by sgarciac** [comment]
yes, thanks!

**Comment by sgarciac** [comment]
To fix this issue, we'll need of course a more complex parser for the query expressions. 
I'll put this on my todo list.

**Comment by sgarciac** [comment]
Silly me, this is already supported, using quoted strings. i.e.:

```sh
./fuego query '"$name" == "sergio"'

./fuego query people '"$name" == "sergio"'
```

```json
[
{
    "CreateTime": "2020-12-02T19:55:46.930316Z",
    "Data": {
        "$name": "sergio"
    },
    "ID": "vQzrZGnvkv0mIGWiWj1c",
    "ReadTime": "2020-12-02T19:56:18.367617Z",
    "UpdateTime": "2020-12-02T19:55:46.930316Z"
}
]

```
