### ISSUE TITLE
Unexpected behavior when using with firestore emulator

### ISSUE THREAD

**Issue by othondev** [sgarciac/fuego#30]
When I used the Fuego cli to add a new collection or document these changes don't reflect in firestore emulator UI and vice versa.

Step to reproduce:
1- set FIRESTORE_EMULATOR_HOST to localhost:8080
2- run the command: fuego add [collectionName] .collection.json
3- check if collection was added: fuego query [collectionName]
4- go to http://localhost:4000/firestore

Bug:
The changes didn't appear in the emulator UI.
Expected:
All collections added in emulator UI or Fuego CLI should appear in both interfaces.

![Screen Capture_select-area_20210106113132](https://user-images.githubusercontent.com/28935584/103718718-275dee00-5013-11eb-9700-2b6afa1ae18a.gif)

**Comment by sgarciac** [comment]
Hello @othondev, thanks for excellent bug report, could you try again using the -p option to set a project?, i.e.
```fuego add -p test memberstats ./test.json```

**Comment by othondev** [comment]
It's working with me. Thank you a lot.
