### ISSUE TITLE
"Fuego set" creates repeated document ids

### ISSUE THREAD

**Issue by Gricardov** [sgarciac/fuego#34]
Hi chamo.
I wanted to emulate a bulk update with fuego, so I wrote a set command inside a loop. This is my code:

for i in $(jq -r ".[] | .ID" requests.json)
  do
        fuego set --merge solicitudes $i '{"version": 2}'
done

I'm using jq and bash to run this script. When I use echo $i, it shows all my ids correctly, but when I use the fuego command, it keeps creating new documents with duplicate ids. I tried leaving just one element in the array and it works as expected!
I would like to know what is going on and how to fix it.

Thanks in advance

**Comment by sgarciac** [comment]
@Gricardov chamo, that's really strange since documents with duplicate ids are not supposed to be possible :thinking: 
Can I see what your requests.json look like?

**Comment by sgarciac** [comment]
I was not able to reproduce.
