### ISSUE TITLE
Remove command?

### ISSUE THREAD

**Issue by tripflex** [sgarciac/fuego#4]
Would it be possible to add a remove command?  Reason being, Google IoT requires a-z or A-Z for device ID's -- so if fuego creates a device and it starts with a number, i need to remove the collection but don't see any way to do that with fuego

**Comment by sgarciac** [comment]
Hi, the reason fuego does not include a remove collection command is that there is one in the firebase CLI (and, because of the way firestore works, it's not trivial to implement)

**Comment by tripflex** [comment]
@sgarciac sorry i meant to say **Document** not **Collection**, i assume the same still applies though?

**Comment by sgarciac** [comment]
well, it depends. Deleting a document is simple unless you expect it to delete possible sub-collections recursively. It's not that it would be hard to write, but I'm still pondering if I want to keep fuego as a thin wrapper over the firestore API (with every single fuego invocation only calling the API once) or add some more logic. Right now, I'm keeping it simple. 

Anyway, it still makes sense to add a non recursive delete command, thanks for the suggestion, I'll add it to the todo list.

**Comment by sgarciac** [comment]
Hacktoberfest: This is an easy one for a go programmer of any level! anyone interested, leave a message here and I'll write a description of the task.
