### ISSUE TITLE
About 0.34.0 release

### ISSUE THREAD

**Issue by chenrui333** [sgarciac/fuego#87]
👋 it looks like 0.34.0 release was not completed (i.e. this action run failed, https://github.com/sgarciac/fuego/actions/runs/5917884582/job/16046657054), raise this issue for some awareness. Thanks!

relates to Homebrew/homebrew-core#139991

**Comment by chenrui333** [comment]
close via 
![image](https://github.com/sgarciac/fuego/assets/1580956/272e0a93-fc7d-49fa-bc12-f8317547534c)

**Comment by sgarciac** [comment]
yup, thanks
