### ISSUE TITLE
Add support for adding a collection from json string

### ISSUE THREAD

**Issue by swidnikk** [sgarciac/fuego#9]
Happy to have found your tool here. I'm working to migrate one db to another, I used the query command to save an array of json objects and this works fine. 

`$ fuego query someCollection > someCollection.array.txt`

Where someCollection.array.txt looks like the following,
```
[
 { "property": value },
 { "property": value },
 { "property": value }
...
]

```

Next, I'd like to use the output above to add to a collection e.g. 
```$ fuego add collection ./someCollection.array.txt```

Currently it doesn't seem that this is possible!

Alternatively query might output json
`$ fuego query someCollection > someCollection.json` 

...
{ someCollection:
   [
      { "property": value },
      { "property": value },
      { "property": value }
   ]
}
...

followed by this, 
`$ fuego add someCollection.json`

**Comment by sgarciac** [comment]
Hi, @swidnikk , thanks for the suggestion. For migrations, tho, have you had a look at the import/export official firebase utilities? https://firebase.google.com/docs/firestore/manage-data/export-import
