### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by deepanchal** [sgarciac/fuego#94]
## Description

I downloaded `0.34.0` from releases page to perform delete field operation as specified in README.md, but I couldn't use that feature unless I build from master branch. It's not really an issue but if anyone were to use new features specified in README from old release binary, it wouldn't work for them.

Therefore, I just wanted to request a new release which will now contain these new features:
- https://github.com/sgarciac/fuego/commit/1a61abc55267ce756d8159f284d2faf3f757ec48
- https://github.com/sgarciac/fuego/commit/c709dfa5f5ec1634c495fc8cc9f183fd7d77d15d

**Comment by sgarciac** [comment]
thanks. Unfortunately my release github action is broken, but I'll try to find some time to have a look at it.

**Comment by deepanchal** [comment]
Thanks! If I get a chance, I will try to open a pr to fix it :)

**Comment by sgarciac** [comment]
@deepanchal I created a release with the latest changes. I'll try to create a snap release later.
